name: Tennis Poller (every 5 min)

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

concurrency:
  group: tennis-poller
  cancel-in-progress: true

jobs:
  poll:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run one tick
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          APP_TZ: Europe/Helsinki
          DATA_SOURCE: sofascore
        run: python gha_worker.py
